// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xejdiwkgsdeolkhimrbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlamRpd2tnc2Rlb2xraGltcmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTM3ODYsImV4cCI6MjA3Mjk2OTc4Nn0.kP2FgEZ9SQshLHeq6RtQvsItIUhu0g1TvJqnOH8HWiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});